using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Rasa.Services.Preloader
{
    using Structures.World;

    /// <summary>
    /// One creature row per named boss the mining placed: faction 0 (Bane), the client's own
    /// creature name id, and the family's _Boss entity class. Run speed 9 and walk speed 5, as every
    /// other hostile creature row has them, so a boss chases.
    ///
    /// 64 bosses across 15 zones, ids from 520001. Bosses the fork
    /// already carries are not repeated here; they get a spawnpool row against the id they already have.
    ///
    /// Generated by world/tools/npcmine/gen_boss_spawns.py - see that file for where each field comes
    /// from, and world/boss_spawns.csv for the same rows with their sources.
    /// </summary>
    public class BossCreaturePreloader : PreloaderBase, IPreloader
    {
        public void Preload(MigrationBuilder migrationBuilder)
        {
            Insert(migrationBuilder, CreatureEntry.TableName, typeof(CreatureEntry));
        }

        protected override IEnumerable<object[]> GetRows()
        {
            yield return new object[] { 520001, "Thraxus Machina Super Soldier - Abyss", 24085, 0, 46, 5100, 9734, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520002, "Atta Imperial Guard - Ashen Desert", 22627, 0, 44, 4900, 9952, 9, 5, 1, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520003, "Overseer Himbri - Ashen Desert", 10504, 0, 44, 4900, 9475, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520004, "Overseer Mitecht - Ashen Desert", 10504, 0, 44, 4900, 9792, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520005, "Overseer Naxveik - Ashen Desert", 10504, 0, 44, 4900, 9353, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520006, "Overseer Ulovik - Ashen Desert", 10504, 0, 44, 4900, 9363, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520007, "Thrax Overseer Exing - Ashen Desert", 10504, 0, 44, 4900, 9325, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520008, "Karem Zul - Bootcamp", 21882, 0, 3, 800, 6744, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520009, "The Collector - Bootcamp", 10502, 0, 3, 800, 6736, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520010, "The Dissector - Bootcamp", 10502, 0, 3, 800, 6737, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520011, "Excavator Xang - Caves of Donn", 10504, 0, 11, 1600, 6756, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520012, "Hominis Machina Lt. Casper - Crater Lake Research", 21474, 0, 9, 1400, 6739, 9, 5, 18, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520013, "Executioner Derge - Crucible", 10504, 0, 47, 5200, 9179, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520014, "Thrax Commander - Crucible", 10504, 0, 47, 5200, 10629, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520015, "Caretaker Mordra - Divide", 10321, 0, 20, 2500, 7018, 9, 5, 16, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520016, "Queen Stazzle - Divide", 6263, 0, 20, 2500, 7020, 9, 5, 1, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520017, "Rotting Sal - Divide", 21474, 0, 20, 2500, 6758, 9, 5, 18, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520018, "Splatter - Divide", 10310, 0, 20, 2500, 7019, 9, 5, 11, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520019, "The Meat Grinder - Divide", 10504, 0, 20, 2500, 6712, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520020, "Master Gas Harvester Phuumz - Howling Maw", 7078, 0, 48, 5300, 9652, 9, 5, 1, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520021, "Security Overseer Maithan - Howling Maw", 10504, 0, 48, 5300, 9802, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520022, "Alpha Class Recon Predator - Incline", 3902, 0, 42, 4700, 10439, 9, 5, 1, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520023, "Overseer Nyxroq - Incline", 10504, 0, 42, 4700, 6989, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520024, "Overseer Turquar - Incline", 10504, 0, 42, 4700, 6904, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520025, "Taskmaster Puuk - Incline", 10504, 0, 42, 4700, 6905, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520026, "Thrall Bruunk - Incline", 10504, 0, 42, 4700, 6906, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520027, "Thrall Yquog - Incline", 10504, 0, 42, 4700, 6907, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520028, "Caretaker Fik - Marshes", 10321, 0, 38, 4300, 8756, 9, 5, 16, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520029, "Commander Barzak - Marshes", 10504, 0, 38, 4300, 8757, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520030, "Commander Sto - Marshes", 10504, 0, 38, 4300, 8758, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520031, "Daddy Long-Legs - Marshes", 24548, 0, 38, 4300, 8917, 9, 5, 1, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520032, "Overseer Cast'ka - Marshes", 10504, 0, 38, 4300, 8548, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520033, "Overseer Koorva - Marshes", 10504, 0, 38, 4300, 8833, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520034, "Overseer Nivvik - Marshes", 10504, 0, 38, 4300, 8624, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520035, "Overseer Vesh - Marshes", 10504, 0, 38, 4300, 8834, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520036, "Seymour - Marshes", 22980, 0, 38, 4300, 8916, 9, 5, 1, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520037, "Davinx - Palisades", 10502, 0, 28, 3300, 9562, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520038, "Fithik Hive Master - Palisades", 10323, 0, 28, 3300, 6690, 9, 5, 44, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520039, "Hygax - Palisades", 10333, 0, 28, 3300, 9174, 9, 5, 30, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520040, "Kennilaxx - Palisades", 10510, 0, 28, 3300, 6706, 9, 5, 33, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520041, "Lawfoid - Palisades", 10502, 0, 28, 3300, 9563, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520042, "Mirtanz - Palisades", 10502, 0, 28, 3300, 9564, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520043, "Overseer Urm - Palisades", 10504, 0, 28, 3300, 20000016, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520044, "Shahrbaraz - Palisades", 10319, 0, 28, 3300, 7023, 9, 5, 4, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520045, "Sinatrix - Palisades", 10502, 0, 28, 3300, 9565, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520046, "Warnet Queen - Palisades", 6263, 0, 28, 3300, 461, 9, 5, 1, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520047, "Cracked Tooth - Plains", 10325, 0, 40, 4500, 8864, 9, 5, 1, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520048, "Overseer Quarm - Plains", 10504, 0, 40, 4500, 6991, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520049, "Plains Devil Lord - Plains", 10317, 0, 40, 4500, 8786, 9, 5, 1, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520050, "The Red Kraken - Plains", 22627, 0, 40, 4500, 8897, 9, 5, 1, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520051, "Goliath - Plateau", 25413, 0, 32, 3700, 8654, 9, 5, 1, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520052, "Inquisitor Krakatus - Plateau", 10502, 0, 32, 3700, 8605, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520053, "Mox Alpha Male - Plateau", 22977, 0, 32, 3700, 8797, 9, 5, 22, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520054, "Thrax Preceptor Vorvaak - Plateau", 10504, 0, 32, 3700, 6874, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520055, "Cavalon - Pools", 24084, 0, 35, 4000, 10014, 9, 5, 42, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520056, "Goriam - Pools", 10310, 0, 35, 4000, 10017, 9, 5, 11, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520057, "Iceram - Pools", 3902, 0, 35, 4000, 10021, 9, 5, 1, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520058, "Irix - Pools", 10504, 0, 35, 4000, 10016, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520059, "Krammitron - Pools", 24548, 0, 35, 4000, 10018, 9, 5, 1, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520060, "Lililax - Pools", 10504, 0, 35, 4000, 10005, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520061, "Orax - Pools", 21882, 0, 35, 4000, 10015, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520062, "Overseer Prysiam - Pools", 10504, 0, 35, 4000, 8631, 9, 5, 34, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520063, "Painrox - Thunderhead", 25413, 0, 45, 5000, 9809, 9, 5, 1, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 520064, "Tiamox - Thunderhead", 22627, 0, 45, 5000, 9787, 9, 5, 1, 0, 0, 0, 0, 0, 0, 0 };
        }
    }
}
