using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Rasa.Services.Preloader
{
    using Structures.World;

    /// <summary>
    /// One creature row per per-class class trainer.
    ///
    /// Generated by tools/gen_class_trainers.py from the client's own marker texts and trainer
    /// dialog. Ids start at 501001, clear of the service NPCs at 500001-500325 and of the block
    /// Fix_service_npcs purges.
    /// </summary>
    public class ClassTrainerCreaturePreloader : PreloaderBase, IPreloader
    {
        public void Preload(MigrationBuilder migrationBuilder)
        {
            Insert(migrationBuilder, CreatureEntry.TableName, typeof(CreatureEntry));
        }

        protected override IEnumerable<object[]> GetRows()
        {
            yield return new object[] { 501001, "Soldier Trainer: Alia Das", 20975, 1, 5, 555, 6922, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501002, "Specialist Trainer: Alia Das", 20975, 1, 5, 555, 6923, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501003, "Commando Trainer: Alia Das", 20975, 1, 5, 555, 6912, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501004, "Ranger Trainer: Alia Das", 20975, 1, 5, 555, 6919, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501005, "Sapper Trainer: Alia Das", 20975, 1, 5, 555, 6920, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501006, "Biotechnician Trainer: Alia Das", 20975, 1, 5, 555, 6911, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501007, "Soldier Trainer: Twin Pillars", 20975, 1, 5, 555, 6922, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501008, "Specialist Trainer: Twin Pillars", 20975, 1, 5, 555, 6923, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501009, "Commando Trainer: Twin Pillars", 20975, 1, 5, 555, 6912, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501010, "Ranger Trainer: Twin Pillars", 20975, 1, 5, 555, 6919, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501011, "Sapper Trainer: Twin Pillars", 20975, 1, 5, 555, 6920, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501012, "Biotechnician Trainer: Twin Pillars", 20975, 1, 5, 555, 6911, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501013, "Commando Trainer: Fort Defiance", 20975, 1, 5, 555, 6912, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501014, "Ranger Trainer: Fort Defiance", 20975, 1, 5, 555, 6919, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501015, "Sapper Trainer: Fort Defiance", 20975, 1, 5, 555, 6920, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501016, "Biotechnician Trainer: Fort Defiance", 20975, 1, 5, 555, 6911, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501017, "Grenadier Trainer: Fort Defiance", 20975, 1, 5, 555, 6916, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501018, "Guardian Trainer: Fort Defiance", 20975, 1, 5, 555, 6917, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501019, "Sniper Trainer: Fort Defiance", 20975, 1, 5, 555, 6921, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501020, "Spy Trainer: Fort Defiance", 20975, 1, 5, 555, 6924, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501021, "Demolitionist Trainer: Fort Defiance", 20975, 1, 5, 555, 6913, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501022, "Engineer Trainer: Fort Defiance", 20975, 1, 5, 555, 6914, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501023, "Medic Trainer: Fort Defiance", 20975, 1, 5, 555, 6918, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501024, "Exobiologist Trainer: Fort Defiance", 20975, 1, 5, 555, 6915, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501025, "Commando Trainer: Torden Mires", 20975, 1, 5, 555, 6912, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501026, "Ranger Trainer: Torden Mires", 20975, 1, 5, 555, 6919, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501027, "Sapper Trainer: Torden Mires", 20975, 1, 5, 555, 6920, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501028, "Biotechnician Trainer: Torden Mires", 20975, 1, 5, 555, 6911, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501029, "Grenadier Trainer: Torden Mires", 20975, 1, 5, 555, 6916, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501030, "Guardian Trainer: Torden Mires", 20975, 1, 5, 555, 6917, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501031, "Sniper Trainer: Torden Mires", 20975, 1, 5, 555, 6921, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501032, "Spy Trainer: Torden Mires", 20975, 1, 5, 555, 6924, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501033, "Demolitionist Trainer: Torden Mires", 20975, 1, 5, 555, 6913, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501034, "Engineer Trainer: Torden Mires", 20975, 1, 5, 555, 6914, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501035, "Medic Trainer: Torden Mires", 20975, 1, 5, 555, 6918, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501036, "Exobiologist Trainer: Torden Mires", 20975, 1, 5, 555, 6915, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501037, "Soldier Trainer: Ashen Desert", 20975, 1, 5, 555, 6922, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 501038, "Specialist Trainer: Ashen Desert", 20975, 1, 5, 555, 6923, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
        }
    }
}
