using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Rasa.Services.Preloader
{
    using Structures.World;

    /// <summary>
    /// One creature row per mission NPC: the roster name id, a swapset class for its race and gender, level 10, pinned (run and walk speed 0).
    ///
    /// Generated by world/tools/npcmine/gen_mission_npcs.py from npc_locations.csv: the named mission NPCs
    /// whose place a mission sentence states outright ("Report to X at Y"), at the map marker of that
    /// place, snapped to the walkable navmesh. Ids start at 510001 so nothing seeded before is disturbed.
    /// </summary>
    public class MissionNpcCreaturePreloader : PreloaderBase, IPreloader
    {
        public void Preload(MigrationBuilder migrationBuilder)
        {
            Insert(migrationBuilder, CreatureEntry.TableName, typeof(CreatureEntry));
        }

        protected override IEnumerable<object[]> GetRows()
        {
            yield return new object[] { 510001, "Archaeologist Wynne Topper - Twin Pillars", 3846, 1, 10, 1000, 10650, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510002, "Brigadier General Beacham - Alia Das", 3846, 1, 10, 1000, 6733, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510003, "Commander Armstrong - Twin Pillars Outpost", 3846, 1, 10, 1000, 10588, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510004, "Dr. Elise Corman - Alia Das", 6339, 1, 10, 1000, 2989, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510005, "George Corman - Ranja Gorge", 6339, 1, 10, 1000, 5425, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510006, "Sapper Trainer Kincaid - Alia Das", 3846, 1, 10, 1000, 6932, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510007, "Captain Daris Linier - White Oasis Post", 3846, 1, 10, 1000, 9358, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510008, "Captain Flynn Harris - Ashoka Settlement", 3846, 1, 10, 1000, 9263, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510009, "Captain Marcus Emmons - Stonewall Ridge", 3846, 1, 10, 1000, 9300, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510010, "Colonel Mason Linier - Shadow's Edge Post", 3846, 1, 10, 1000, 9260, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510011, "Ida Hayner - Shadow's Edge Post", 3848, 1, 10, 1000, 9288, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510012, "Lieutenant Dania Fontecilla - White Oasis Post", 3846, 1, 10, 1000, 9474, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510013, "Lieutenant Jan Blood - Boneyard Outpost", 3846, 1, 10, 1000, 9305, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510014, "Mechanic Raji Lasat - Ashoka Settlement", 7776, 1, 10, 1000, 9270, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510015, "Awol Captain Cheung - Staal", 3846, 1, 10, 1000, 9154, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510016, "Awol Lieutenant Deirdre - Staal", 3848, 1, 10, 1000, 9163, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510017, "Awol Sergeant Breiburg - Awol Camp", 3846, 1, 10, 1000, 9153, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510018, "Awol Sergeant Melching - Awol Camp", 3846, 1, 10, 1000, 9156, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510019, "Captain DeLisi - Outpost Intrepid", 3846, 1, 10, 1000, 9059, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510020, "Captain Kelly - Outpost Intrepid", 3846, 1, 10, 1000, 9797, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510021, "Captain Tiersky - Prometheus Outpost", 3846, 1, 10, 1000, 9214, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510022, "Corporal Fiorella - Outpost Intrepid", 3846, 1, 10, 1000, 9157, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510023, "Intelligence Officer D'Ambrose - Outpost Intrepid", 3846, 1, 10, 1000, 9161, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510024, "Kappa Grupa Lohen - Staal", 7776, 1, 10, 1000, 9071, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510025, "Labbna Grupa Rigs - Staal", 7776, 1, 10, 1000, 9064, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510026, "Labbna Sigal Haggus - Staal", 7776, 1, 10, 1000, 9065, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510027, "Larai Grupa Vitto - Staal", 7776, 1, 10, 1000, 9066, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510028, "Larai Sigal Tempa - Staal", 7776, 1, 10, 1000, 9067, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510029, "Larai Zupa Madias - Prometheus Outpost", 7776, 1, 10, 1000, 9205, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510030, "Lieutenant Sherer - Outpost Intrepid", 3848, 1, 10, 1000, 9158, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510031, "Major Keplinger - Prometheus Outpost", 3846, 1, 10, 1000, 9208, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510032, "Merchant Cugin - Staal Centrum", 7776, 1, 10, 1000, 9137, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510033, "Merchant Vargo - Staal Centrum", 7776, 1, 10, 1000, 9138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510034, "Private Drake - Outpost Intrepid", 3846, 1, 10, 1000, 9061, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510035, "Special Agent Capriulo - Staal", 3846, 1, 10, 1000, 10301, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510036, "Viddea Scientist Eugin - Staal", 7776, 1, 10, 1000, 10303, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510037, "Viddia Grupa Donal - Staal", 7776, 1, 10, 1000, 9068, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510038, "Supervisor Sheira - Incurables Ward", 7776, 1, 10, 1000, 9517, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510039, "Captain Howry - E104", 3846, 1, 10, 1000, 9198, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510040, "Commander Darren - Thunderhead Base", 3846, 1, 10, 1000, 10150, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510041, "Corporal MacGruber - E104", 3846, 1, 10, 1000, 9196, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510042, "Enforcer Bonree - Larai Outpost", 7776, 1, 10, 1000, 9784, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510043, "Field Sgt. Barnes - Eastern Rim", 3846, 1, 10, 1000, 10319, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510044, "Field Sgt. Eiserloh - Vashtar Pass", 3846, 1, 10, 1000, 10313, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510045, "Scientist Irial - Viddia Outpost", 7776, 1, 10, 1000, 9190, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510046, "Sergeant Dempster - E104", 3846, 1, 10, 1000, 9199, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510047, "Sigal Cisra - Larai Outpost", 7776, 1, 10, 1000, 9193, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510048, "Sigal Swona - Viddia Outpost", 7776, 1, 10, 1000, 10317, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510049, "Zupar Dyro - Larai Outpost", 7776, 1, 10, 1000, 9191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510050, "Agent Maxwell - Tantalus Base", 3846, 1, 10, 1000, 10460, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510051, "Corporal Cottman - Charon's Crossing", 3846, 1, 10, 1000, 9226, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510052, "General Perry - Tantalus Base", 3846, 1, 10, 1000, 9599, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510053, "Labbna Trader Joss - Tantalus Base", 7776, 1, 10, 1000, 9741, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510054, "Larai Zupa Monlo - Tampeii Settlement", 7776, 1, 10, 1000, 9620, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510055, "Penumbra Agent Crawford - Penumbra Section 3", 3846, 1, 10, 1000, 9233, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510056, "Private Heard - Icarus Outpost", 3846, 1, 10, 1000, 9228, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510057, "Professor Whitney - Icarus Post", 3848, 1, 10, 1000, 10428, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510058, "Recon Officer Granger - Brimstone Falls", 3846, 1, 10, 1000, 9661, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510059, "Researcher Dalton - Tampeii Settlement", 3846, 1, 10, 1000, 10432, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510060, "The Director - Tantalus Base", 3846, 1, 10, 1000, 9237, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510061, "Xenobiologist Stanzler - Icarus Outpost", 3846, 1, 10, 1000, 9623, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510062, "Dr. Mathias Sandorf - Omega Labs", 3846, 1, 10, 1000, 10473, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510063, "Colonel Deiley - Ortho", 3846, 1, 10, 1000, 7025, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510064, "Coordinator Maila - Mires Post", 3846, 1, 10, 1000, 4473, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510065, "Coordinator Melsi - Ortho", 3846, 1, 10, 1000, 4409, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510066, "Field Commander Foletto - Nyxroq Trench", 3846, 1, 10, 1000, 6963, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510067, "Gunnery Sergeant Obahmi - Torden Incline", 3846, 1, 10, 1000, 6962, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510068, "Lieutenant Epp - Nyxroq Trench", 3846, 1, 10, 1000, 4419, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510069, "Major Nicholson - Nyxroq Post", 3848, 1, 10, 1000, 7005, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510070, "Medic Rahish - Ortho Post", 3846, 1, 10, 1000, 10334, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510071, "Private Parsons - Plains Post", 3846, 1, 10, 1000, 10270, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510072, "Protector Starl - Ortho", 7034, 1, 10, 1000, 4415, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510073, "Retread Otto - Ortho Post", 3846, 1, 10, 1000, 8550, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510074, "Salvage Master Orto - Ortho Post", 7776, 1, 10, 1000, 4474, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510075, "Science Officer Brandeis - Pax Oasis", 3846, 1, 10, 1000, 4684, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510076, "Science Officer Collier - Raintree Post", 3846, 1, 10, 1000, 4420, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510077, "Supply Sergeant Otto - Ortho Post", 3846, 1, 10, 1000, 10272, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510078, "Dr. Robertson - Fort Haroun", 3846, 1, 10, 1000, 8669, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510079, "Dr. Torpor - Fort Haroun", 3846, 1, 10, 1000, 10297, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510080, "General Mondragon - Fort Haroun", 3846, 1, 10, 1000, 8656, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510081, "Field Medic Casey - Field Medic Casey", 3846, 1, 10, 1000, 8685, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510082, "Agent Zim - Irendas Colony", 3848, 1, 10, 1000, 9008, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510083, "Captain Reyko - Irendas Colony", 3846, 1, 10, 1000, 9007, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510084, "Colonel Franks - Mt. Hellas Outpost", 3846, 1, 10, 1000, 5439, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510085, "Colonel Whitaker - Irendas Colony", 3846, 1, 10, 1000, 5428, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510086, "Dr. Finobee - Irendas Colony", 3846, 1, 10, 1000, 6484, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510087, "Drill Sergeant Luter - Irendas Colony", 3846, 1, 10, 1000, 9469, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510088, "Engineer Tralos - Irendas Colony", 3846, 1, 10, 1000, 9011, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510089, "General Creelig - Irendas Colony", 3846, 1, 10, 1000, 9364, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510090, "Lieutenant Commander Michan - Irendas Colony", 3846, 1, 10, 1000, 9133, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510091, "Lieutenant Liu - Eir Crater", 3848, 1, 10, 1000, 8856, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510092, "Major Silvia - Irendas Colony", 3846, 1, 10, 1000, 8782, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510093, "Master Salvager Miru - Irendas Colony", 3846, 1, 10, 1000, 8839, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510094, "Senior Quartermaster Hacienda - Irendas Colony", 3846, 1, 10, 1000, 8771, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510095, "Sergeant Navaset - Irendas Colony", 3846, 1, 10, 1000, 10612, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510096, "Lieutenant Donners - Kardash Atta Colony", 3848, 1, 10, 1000, 10465, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510097, "Sergeant Phenix - Phanin Research Facility", 3846, 1, 10, 1000, 9141, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510098, "Agent Cicely - Foreas Base", 3848, 1, 10, 1000, 6992, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510099, "Agent Franz - Foreas Base", 3846, 1, 10, 1000, 6945, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510100, "Captain Rankin - Foreas Base", 3846, 1, 10, 1000, 6985, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510101, "Dr. Hansen - Foreas Base", 3846, 1, 10, 1000, 6951, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510102, "Dr. Kibner - Foxtrot Outpost", 3846, 1, 10, 1000, 6952, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510103, "Dr. Sherman - Delta Outpost", 3846, 1, 10, 1000, 6953, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510104, "Elder Q'uoa - Thoria Das", 7035, 1, 10, 1000, 10306, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510105, "Field Lt. McMurray - Foreas Base", 3846, 1, 10, 1000, 193, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510106, "Field Lt. Quinn - Foreas Base", 3846, 1, 10, 1000, 191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510107, "Lieutenant McDowell - Delta Outpost", 3846, 1, 10, 1000, 4839, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510108, "Lieutenant Seguine - Nidu Dav", 3846, 1, 10, 1000, 7033, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510109, "Line Capt. Dobbs - Thoria Das", 3846, 1, 10, 1000, 2993, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510110, "Recon Officer Stevens - Foreas Base", 3846, 1, 10, 1000, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510111, "Sergeant Hawthorne - Foxtrot Outpost", 3846, 1, 10, 1000, 4737, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510112, "Sergeant Spencer - Foxtrot Outpost", 3846, 1, 10, 1000, 6695, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510113, "Sergeant Zuelke - Hydro Plant", 3846, 1, 10, 1000, 4837, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510114, "Sgt. Yeager - Hydro Plant", 3846, 1, 10, 1000, 3007, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510115, "Shaman Horea - Thoria Das", 7035, 1, 10, 1000, 3000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510116, "Spec. Kerr - Foreas Base", 3846, 1, 10, 1000, 3009, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510117, "Warrior Mela - Thoria Das", 7034, 1, 10, 1000, 3029, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510118, "Field Ranger Kearney - Timora Mines", 3846, 1, 10, 1000, 2996, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510119, "Sergeant Pastre - Timora Mines", 3846, 1, 10, 1000, 6878, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510120, "Airman Hamilton - Torcastra Prison", 3846, 1, 10, 1000, 9406, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510121, "Captain McShay - Staging Point", 3846, 1, 10, 1000, 10230, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510122, "Captain Tayros - Fort Dew", 3846, 1, 10, 1000, 10203, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510123, "Commander Aldrin - Cumbria Research Facility", 3846, 1, 10, 1000, 10592, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510124, "Corporal Hutchison - Cumbria Research Facility", 3846, 1, 10, 1000, 2931, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510125, "Field Commander Twitty - Staging Point", 3846, 1, 10, 1000, 10232, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510126, "Field Lt. Brody - Walk of Giants", 3846, 1, 10, 1000, 2946, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510127, "Field Technician McCain - Staging Point", 3846, 1, 10, 1000, 10231, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510128, "Private Fagan - Viands Village", 3846, 1, 10, 1000, 10237, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510129, "Private Richardson - River-base Krimm", 3846, 1, 10, 1000, 10236, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510130, "Private Robertson - Fort Dew", 3846, 1, 10, 1000, 10235, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510131, "Ranger Cyrida - Hightower Outpost", 7034, 1, 10, 1000, 2958, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510132, "Ranger Gorodai - Treeback Ridge", 7034, 1, 10, 1000, 195, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510133, "Ranger Jorai - Viands Village", 7034, 1, 10, 1000, 2960, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510134, "Sergeant Barrasso - River-base Krimm", 3846, 1, 10, 1000, 10220, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510135, "Sergeant Mullen - River-base Krimm", 3846, 1, 10, 1000, 10221, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510136, "Thomas Jansona - Cumbria Weald", 3846, 1, 10, 1000, 2940, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510137, "Valerie Corman - Cumbria Research Facility", 6339, 1, 10, 1000, 7031, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510138, "Warden Brocail - Walk of Giants", 7034, 1, 10, 1000, 2947, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510139, "Warden Kahlee - Walk of Giants", 7034, 1, 10, 1000, 2949, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510140, "Warden Lagori - Walk of Giants", 7034, 1, 10, 1000, 2948, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510141, "Captain Quanos - Dia Uyona", 3846, 1, 10, 1000, 9557, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510142, "Colonel Sherk - Gangus Outpost", 3846, 1, 10, 1000, 9375, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510143, "Commander Lovell - Gangus Outpost", 3846, 1, 10, 1000, 10589, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510144, "Field Commander Welling - Dia Moroyo", 3846, 1, 10, 1000, 9713, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510145, "Major Jones - Gangus Supply Annex", 3846, 1, 10, 1000, 9546, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510146, "Major Phych - Gangus Supply Annex", 3846, 1, 10, 1000, 9426, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510147, "Recon Commander McReddy - Dia Toma", 3846, 1, 10, 1000, 9651, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510148, "Scholar Rui - Dia Uyona", 7034, 1, 10, 1000, 9625, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510149, "Sergeant Fonseca - Howling Maw", 3846, 1, 10, 1000, 9531, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510150, "Spec-Ops Quartermaster Olivia - Gangus Outpost", 3848, 1, 10, 1000, 9513, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510151, "Doctor Splicer - Bioresearch Wing", 3846, 1, 10, 1000, 9840, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510152, "Elder Hathen - Velon Hollow", 7035, 1, 10, 1000, 10209, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510153, "Captain North - Fort Virgil", 3846, 1, 10, 1000, 9697, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510154, "Chief Medical Officer Reynolds - Fort Virgil", 3846, 1, 10, 1000, 9699, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510155, "Commander Merrick - Mal Dys", 3846, 1, 10, 1000, 9333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510156, "Fortuna Corman - Mal Dys", 6340, 1, 10, 1000, 9331, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510157, "Reception Officer Arvis - Fort Virgil", 3846, 1, 10, 1000, 9701, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510158, "Specialist Crowley - Antaeus Hollow", 3846, 1, 10, 1000, 9691, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510159, "Supply Sergeant Chen - Fort Virgil", 3846, 1, 10, 1000, 9698, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510160, "Elder Toida - Paludos", 7035, 1, 10, 1000, 3125, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510161, "Field Medic DuBois - Falcon Hold", 3846, 1, 10, 1000, 8597, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510162, "Lieutenant Morrison - Falcon Hold", 3846, 1, 10, 1000, 3113, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510163, "MP Price - Paludos", 3846, 1, 10, 1000, 3120, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510164, "Ranger Taavik - Paludos", 7034, 1, 10, 1000, 8641, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510165, "Researcher Vetter - Falcon Hold", 3846, 1, 10, 1000, 3118, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510166, "Retread Kline - Paludos", 3846, 1, 10, 1000, 8556, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510167, "Retread Samuel - Bane Refueling Station", 3846, 1, 10, 1000, 8855, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510168, "Retread Vincent - Retread City", 3846, 1, 10, 1000, 8552, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510169, "Sergeant Elway - Falcon Hold", 3846, 1, 10, 1000, 3114, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510170, "Sergeant Fitz - Paludos", 3846, 1, 10, 1000, 8921, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510171, "Sergeant Starling - Paludos", 3846, 1, 10, 1000, 3123, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510172, "Shaman Geli - Paludos", 7035, 1, 10, 1000, 3122, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510173, "Bartender McLaughlin - Fort Defiance", 3846, 1, 10, 1000, 6762, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510174, "CID Commander Provost - AFS Criminal Investigation", 3846, 1, 10, 1000, 8575, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510175, "CID Detective Crais - Fort Defiance", 3846, 1, 10, 1000, 8635, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510176, "Colonel Bosley - Camp Resistance", 3846, 1, 10, 1000, 8618, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510177, "Colonel Thibodeau - Wedge Rock Outpost", 3846, 1, 10, 1000, 10273, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510178, "Comm Officer Devinchy - Wedge Rock Outpost", 3846, 1, 10, 1000, 4666, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510179, "Comm Officer McKinley - Wedge Rock Outpost", 3846, 1, 10, 1000, 4674, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510180, "Commander Grissom - Fort Defiance", 3846, 1, 10, 1000, 10587, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510181, "Elder Hundra - New Velon Village", 7035, 1, 10, 1000, 8612, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510182, "Field Lt. Peterson - Fort Defiance", 3846, 1, 10, 1000, 4662, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510183, "Field Sgt. Garde - Valverde Chasm", 3846, 1, 10, 1000, 4665, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510184, "Lieutenant Colonel Doss - Fort Defiance", 3846, 1, 10, 1000, 9781, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510185, "Loremaster Talisen - New Velon Village", 7035, 1, 10, 1000, 8610, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510186, "Luminary Sampei - New Velon Village", 7035, 1, 10, 1000, 8608, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510187, "MP Sergeant Norton - Fort Defiance", 3846, 1, 10, 1000, 8561, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510188, "Private Remick - Wedge Rock Outpost", 3846, 1, 10, 1000, 8632, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510189, "Ranger Kaely - New Velon Village", 7034, 1, 10, 1000, 8609, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510190, "Ranger Porthus - Valverde Chasm", 7034, 1, 10, 1000, 8836, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510191, "Science Officer Clark - Wedge Rock Outpost", 3846, 1, 10, 1000, 4670, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510192, "Senior Engineer Mauer - Fort Defiance", 3846, 1, 10, 1000, 8748, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510193, "Special Agent Perdu - Fort Defiance", 3846, 1, 10, 1000, 6791, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510194, "Captain Danny Bowers - Sanctus Grotto", 3846, 1, 10, 1000, 10178, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510195, "Amee Corman - Retread Camp", 6340, 1, 10, 1000, 4370, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510196, "Corporal Orton - Obelisk", 3846, 1, 10, 1000, 2929, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510197, "Corporal Sheen - East Listening Post", 3846, 1, 10, 1000, 9405, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510198, "Lieutenant Chester - East Listening Post", 3846, 1, 10, 1000, 9404, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510199, "Lieutenant Holloway - Retread Camp", 3846, 1, 10, 1000, 8594, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510200, "Lt. Cujhan - East Listening Post", 3846, 1, 10, 1000, 10284, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510201, "Retread McCormick - Retread Camp", 3846, 1, 10, 1000, 8578, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
            yield return new object[] { 510202, "Scientist Suresh - South Listening Post", 3848, 1, 10, 1000, 9381, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
        }
    }
}
