using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Rasa.Services.Preloader
{
    using Structures.World;

    /// <summary>
    /// npc_package rows for the NPCs whose package id the client's objectiveconversation table gives (npc_package.id is the creature row).
    ///
    /// Generated by world/tools/npcmine/gen_mission_npcs.py from npc_locations.csv: the named mission NPCs
    /// whose place a mission sentence states outright ("Report to X at Y"), at the map marker of that
    /// place, snapped to the walkable navmesh. Ids start at 510001 so nothing seeded before is disturbed.
    /// </summary>
    public class MissionNpcPackagePreloader : PreloaderBase, IPreloader
    {
        public void Preload(MigrationBuilder migrationBuilder)
        {
            Insert(migrationBuilder, NpcPackageEntry.TableName, typeof(NpcPackageEntry));
        }

        protected override IEnumerable<object[]> GetRows()
        {
            yield return new object[] { 510001, 2595, "Archaeologist Wynne Topper" };
            yield return new object[] { 510002, 593, "Brigadier General Beacham" };
            yield return new object[] { 510004, 130, "Dr. Elise Corman" };
            yield return new object[] { 510007, 1476, "Captain Daris Linier" };
            yield return new object[] { 510008, 1412, "Captain Flynn Harris" };
            yield return new object[] { 510009, 1411, "Captain Marcus Emmons" };
            yield return new object[] { 510010, 1389, "Colonel Mason Linier" };
            yield return new object[] { 510015, 1292, "Awol Captain Cheung" };
            yield return new object[] { 510016, 1304, "Awol Lieutenant Deirdre" };
            yield return new object[] { 510017, 1293, "Awol Sergeant Breiburg" };
            yield return new object[] { 510018, 1295, "Awol Sergeant Melching" };
            yield return new object[] { 510019, 1219, "Captain DeLisi" };
            yield return new object[] { 510022, 1296, "Corporal Fiorella" };
            yield return new object[] { 510023, 1229, "Intelligence Officer D'Ambrose" };
            yield return new object[] { 510024, 1222, "Kappa Grupa Lohen" };
            yield return new object[] { 510026, 1232, "Labbna Sigal Haggus" };
            yield return new object[] { 510027, 1225, "Larai Grupa Vitto" };
            yield return new object[] { 510030, 1297, "Lieutenant Sherer" };
            yield return new object[] { 510031, 1337, "Major Keplinger" };
            yield return new object[] { 510032, 1269, "Merchant Cugin" };
            yield return new object[] { 510033, 1271, "Merchant Vargo" };
            yield return new object[] { 510035, 2335, "Special Agent Capriulo" };
            yield return new object[] { 510036, 2337, "Viddea Scientist Eugin" };
            yield return new object[] { 510037, 1227, "Viddia Grupa Donal" };
            yield return new object[] { 510038, 1640, "Supervisor Sheira" };
            yield return new object[] { 510039, 1395, "Captain Howry" };
            yield return new object[] { 510040, 2235, "Commander Darren" };
            yield return new object[] { 510041, 1393, "Corporal MacGruber" };
            yield return new object[] { 510043, 2363, "Field Sgt. Barnes" };
            yield return new object[] { 510044, 2350, "Field Sgt. Eiserloh" };
            yield return new object[] { 510045, 1379, "Scientist Irial" };
            yield return new object[] { 510046, 1396, "Sergeant Dempster" };
            yield return new object[] { 510047, 1390, "Sigal Cisra" };
            yield return new object[] { 510048, 2354, "Sigal Swona" };
            yield return new object[] { 510049, 1380, "Zupar Dyro" };
            yield return new object[] { 510051, 1371, "Corporal Cottman" };
            yield return new object[] { 510052, 1364, "General Perry" };
            yield return new object[] { 510054, 1703, "Larai Zupa Monlo" };
            yield return new object[] { 510055, 1350, "Penumbra Agent Crawford" };
            yield return new object[] { 510056, 1375, "Private Heard" };
            yield return new object[] { 510058, 1749, "Recon Officer Granger" };
            yield return new object[] { 510060, 1346, "The Director" };
            yield return new object[] { 510061, 1706, "Xenobiologist Stanzler" };
            yield return new object[] { 510062, 2472, "Dr. Mathias Sandorf" };
            yield return new object[] { 510063, 795, "Colonel Deiley" };
            yield return new object[] { 510064, 381, "Coordinator Maila" };
            yield return new object[] { 510066, 752, "Field Commander Foletto" };
            yield return new object[] { 510067, 751, "Gunnery Sergeant Obahmi" };
            yield return new object[] { 510068, 2594, "Lieutenant Epp" };
            yield return new object[] { 510069, 776, "Major Nicholson" };
            yield return new object[] { 510070, 2373, "Medic Rahish" };
            yield return new object[] { 510071, 2327, "Private Parsons" };
            yield return new object[] { 510074, 380, "Salvage Master Orto" };
            yield return new object[] { 510077, 2329, "Supply Sergeant Otto" };
            yield return new object[] { 510078, 1048, "Dr. Robertson" };
            yield return new object[] { 510079, 2331, "Dr. Torpor" };
            yield return new object[] { 510080, 1035, "General Mondragon" };
            yield return new object[] { 510081, 1064, "Field Medic Casey" };
            yield return new object[] { 510082, 1201, "Agent Zim" };
            yield return new object[] { 510083, 1200, "Captain Reyko" };
            yield return new object[] { 510084, 521, "Colonel Franks" };
            yield return new object[] { 510085, 1095, "Colonel Whitaker" };
            yield return new object[] { 510086, 545, "Dr. Finobee" };
            yield return new object[] { 510088, 1204, "Engineer Tralos" };
            yield return new object[] { 510089, 1479, "General Creelig" };
            yield return new object[] { 510090, 1280, "Lieutenant Commander Michan" };
            yield return new object[] { 510091, 1119, "Lieutenant Liu" };
            yield return new object[] { 510092, 1099, "Major Silvia" };
            yield return new object[] { 510093, 1114, "Master Salvager Miru" };
            yield return new object[] { 510094, 1098, "Senior Quartermaster Hacienda" };
            yield return new object[] { 510096, 2457, "Lieutenant Donners" };
            yield return new object[] { 510097, 1273, "Sergeant Phenix" };
            yield return new object[] { 510098, 764, "Agent Cicely" };
            yield return new object[] { 510099, 761, "Agent Franz" };
            yield return new object[] { 510100, 758, "Captain Rankin" };
            yield return new object[] { 510104, 2345, "Elder Q'uoa" };
            yield return new object[] { 510105, 98, "Field Lt. McMurray" };
            yield return new object[] { 510108, 802, "Lieutenant Seguine" };
            yield return new object[] { 510109, 32, "Line Capt. Dobbs" };
            yield return new object[] { 510110, 586, "Recon Officer Stevens" };
            yield return new object[] { 510116, 171, "Spec. Kerr" };
            yield return new object[] { 510117, 190, "Warrior Mela" };
            yield return new object[] { 510118, 158, "Field Ranger Kearney" };
            yield return new object[] { 510120, 1527, "Airman Hamilton" };
            yield return new object[] { 510121, 2287, "Captain McShay" };
            yield return new object[] { 510125, 2289, "Field Commander Twitty" };
            yield return new object[] { 510126, 145, "Field Lt. Brody" };
            yield return new object[] { 510127, 2288, "Field Technician McCain" };
            yield return new object[] { 510128, 2294, "Private Fagan" };
            yield return new object[] { 510131, 152, "Ranger Cyrida" };
            yield return new object[] { 510133, 47, "Ranger Jorai" };
            yield return new object[] { 510137, 800, "Valerie Corman" };
            yield return new object[] { 510138, 40, "Warden Brocail" };
            yield return new object[] { 510139, 1316, "Warden Kahlee" };
            yield return new object[] { 510140, 1312, "Warden Lagori" };
            yield return new object[] { 510142, 1487, "Colonel Sherk" };
            yield return new object[] { 510144, 1792, "Field Commander Welling" };
            yield return new object[] { 510147, 1743, "Recon Commander McReddy" };
            yield return new object[] { 510150, 1636, "Spec-Ops Quartermaster Olivia" };
            yield return new object[] { 510152, 2263, "Elder Hathen" };
            yield return new object[] { 510153, 1782, "Captain North" };
            yield return new object[] { 510154, 1783, "Chief Medical Officer Reynolds" };
            yield return new object[] { 510155, 1457, "Commander Merrick" };
            yield return new object[] { 510156, 1460, "Fortuna Corman" };
            yield return new object[] { 510157, 1784, "Reception Officer Arvis" };
            yield return new object[] { 510158, 1777, "Specialist Crowley" };
            yield return new object[] { 510159, 1785, "Supply Sergeant Chen" };
            yield return new object[] { 510160, 288, "Elder Toida" };
            yield return new object[] { 510162, 299, "Lieutenant Morrison" };
            yield return new object[] { 510163, 386, "MP Price" };
            yield return new object[] { 510167, 120, "Retread Samuel" };
            yield return new object[] { 510168, 951, "Retread Vincent" };
            yield return new object[] { 510173, 629, "Bartender McLaughlin" };
            yield return new object[] { 510174, 962, "CID Commander Provost" };
            yield return new object[] { 510175, 963, "CID Detective Crais" };
            yield return new object[] { 510176, 1001, "Colonel Bosley" };
            yield return new object[] { 510178, 389, "Comm Officer Devinchy" };
            yield return new object[] { 510179, 395, "Comm Officer McKinley" };
            yield return new object[] { 510182, 385, "Field Lt. Peterson" };
            yield return new object[] { 510183, 387, "Field Sgt. Garde" };
            yield return new object[] { 510186, 994, "Luminary Sampei" };
            yield return new object[] { 510187, 959, "MP Sergeant Norton" };
            yield return new object[] { 510188, 1015, "Private Remick" };
            yield return new object[] { 510190, 1113, "Ranger Porthus" };
            yield return new object[] { 510191, 407, "Science Officer Clark" };
            yield return new object[] { 510192, 1094, "Senior Engineer Mauer" };
            yield return new object[] { 510193, 639, "Special Agent Perdu" };
            yield return new object[] { 510195, 329, "Amee Corman" };
            yield return new object[] { 510196, 134, "Corporal Orton" };
            yield return new object[] { 510200, 2318, "Lt. Cujhan" };
            yield return new object[] { 510201, 968, "Retread McCormick" };
            yield return new object[] { 510202, 1495, "Scientist Suresh" };
        }
    }
}
