using System.Collections.Generic;

namespace Rasa.Data
{
    /// <summary>
    /// The categories the auction house's browse tab offers. Its search button stays disabled
    /// until one is picked, so every query carries one and the server has to know them all.
    ///
    /// Generated by tools/gen_auction_categories.py from the client's own
    /// generated.client.auctionhouse.categorydata. The name is a path through the item class
    /// naming scheme, so an item belongs to a category when its entity class name begins with
    /// the first part and carries each later part as one of its underscore-separated words:
    /// "Weapon_Pistol" matches Weapon_Avatar_Pistol_Physical_CMN_01_to_04.
    /// </summary>
    public static class AuctionCategory
    {
        public static readonly IReadOnlyDictionary<uint, string> Names = new Dictionary<uint, string>
        {
            [1] = "Weapon",
            [2] = "Weapon_Pistol",
            [3] = "Weapon_Rifle",
            [4] = "Weapon_Shotgun",
            [5] = "Weapon_MachineGun",
            [6] = "Weapon_LeechGun",
            [7] = "Weapon_RPG",
            [8] = "Weapon_RocketLauncher",
            [9] = "Weapon_NetGun",
            [10] = "Weapon_PolarityGun",
            [11] = "Weapon_InjectionGun",
            [12] = "Weapon_PropellantGun",
            [13] = "Weapon_Staff",
            [14] = "Weapon_SniperRifle",
            [15] = "Weapon_Blade",
            [16] = "Armor",
            [17] = "Armor_MotorAssist",
            [18] = "Armor_MotorAssist_Head",
            [21] = "Armor_MotorAssist_Chest",
            [22] = "Armor_MotorAssist_Hands",
            [23] = "Armor_MotorAssist_Legs",
            [24] = "Armor_MotorAssist_Feet",
            [25] = "Armor_Reflective",
            [26] = "Armor_Reflective_Head",
            [29] = "Armor_Reflective_Chest",
            [30] = "Armor_Reflective_Hands",
            [31] = "Armor_Reflective_Legs",
            [32] = "Armor_Reflective_Feet",
            [33] = "Armor_Hazmat",
            [34] = "Armor_Hazmat_Head",
            [37] = "Armor_Hazmat_Chest",
            [38] = "Armor_Hazmat_Hands",
            [39] = "Armor_Hazmat_Legs",
            [40] = "Armor_Hazmat_Feet",
            [41] = "Armor_Graviton",
            [42] = "Armor_Graviton_Head",
            [43] = "Armor_Graviton_UpperFace",
            [44] = "Armor_Graviton_LowerFace",
            [45] = "Armor_Graviton_Chest",
            [46] = "Armor_Graviton_Hands",
            [47] = "Armor_Graviton_Legs",
            [48] = "Armor_Graviton_Feet",
            [49] = "Armor_Stealth",
            [50] = "Armor_Stealth_Head",
            [53] = "Armor_Stealth_Chest",
            [54] = "Armor_Stealth_Hands",
            [55] = "Armor_Stealth_Legs",
            [56] = "Armor_Stealth_Feet",
            [57] = "Armor_MechSuit",
            [58] = "Armor_MechSuit_Head",
            [61] = "Armor_MechSuit_Chest",
            [62] = "Armor_MechSuit_Hands",
            [63] = "Armor_MechSuit_Legs",
            [64] = "Armor_MechSuit_Feet",
            [65] = "Armor_BioSuit",
            [66] = "Armor_BioSuit_Head",
            [69] = "Armor_BioSuit_Chest",
            [70] = "Armor_BioSuit_Hands",
            [71] = "Armor_BioSuit_Legs",
            [72] = "Armor_BioSuit_Feet",
            [73] = "Crafting",
            [74] = "Crafting_Fabrication",
            [75] = "Crafting_Fabrication_Ammunition",
            [76] = "Crafting_Fabrication_Paint",
            [77] = "Crafting_Fabrication_Consumable",
            [78] = "Crafting_Fabrication_Resource",
            [104] = "Crafting_Salvage",
            [105] = "Consumables",
            [106] = "Weapon_Tool",
            [107] = "Consumables_Ammunition",
            [108] = "Consumables_Resources",
            [109] = "Consumables_Explosives",
            [110] = "Consumables_Medical",
            [111] = "Consumables_Dyes",
            [112] = "Consumables_Miscellaneous",
            [113] = "Armor_Accessory",
            [114] = "Armor_Accessory_UpperFace",
            [115] = "Armor_Accessory_LowerFace",
            [116] = "Crafting_Modules",
            [117] = "Crafting_Modules_Armor",
            [118] = "Crafting_Modules_Tools",
            [119] = "Crafting_Modules_Weapons",
            [120] = "Crafting_Mimeogel",
        };
    }
}
